### ISSUE TITLE
Update annonars dependency, adjust to ClinVar protobuf changes

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/mehari#455]
**Is your feature request related to a problem? Please describe.**
We need to update the annonars dependency in mehari. This will trigger some issues in the changed ClinVar protobuf.

**Describe the solution you'd like**
- adjust to these changes
- write out VCV instead of RCV

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tedil** [comment]
Is this still relevant?
